services:
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    pid: host
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./glances.conf:/home/lab/share/glances/glances.conf:ro
      - /mnt/drive1:/mnt/drive1:ro
      - /mnt/drive2:/mnt/drive2:ro
      # - /proc:/host/proc:ro
      # - /sys:/host/sys:ro
      # - /etc:/host/etc:ro
    environment:
      - GLANCES_OPT=-w
    restart: unless-stopped

