services:
  glances:
    container_name: glances
    image: nicolargo/glances:latest-full
    pid: host
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/lab/share/glances/glances.conf:/glances/conf/glances.conf:ro
      - ${DATADRIVE}:${DATADRIVE}:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - GLANCES_OPT=-w
    restart: unless-stopped

  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    user: ${PUID}:${PGID}
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    environment:
      - TZ=${TZ} 
    volumes:
      - ./share/jellyfin/config:/config:rw
      - ./share/jellyfin/cache:/cache:rw
      - ./share/jellyfin/logs:/logs:rw
      - ${DATADRIVE}/media:/media:rw
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri:/dev/dri
