services:

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80/tcp"
    environment:
      TZ: ${TZ}
      PIHOLE_UID: ${PUID}
      PIHOLE_GID: ${PGID}
      FTLCONF_dns_listeningMode: 'all' # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_piholePTR: 'PI.HOLE'
      FTLCONF_dns_revServers: 'true,${LOCAL_NETWORK},${ROUTER_IP},lan'
      FTLCONF_dns_domain_name: 'lan' # required?
      FTLCONF_webserver_api_password: ${FTLCONF_webserver_api_password}
    volumes:
      - ./pihole/etc/pihole:/etc/pihole
    networks:
      - proxy

  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    privileged: true
    volumes:
      - ./home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    devices:
      - /dev/ttyACM0
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      
networks:
  proxy:
